### ISSUE TITLE
Basic rails app + basic view markup + Deployment on Heroku

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#1]
To-Do:

- создать новое приложение (rails new) локально 
- внедрить сетку (Tailwind, Bootstrap, ...)
- создать первую route для дашборда, застилизовать хедер, в котором будет меню и общую область под остальной контент
- провести первый деплой на Heroku
- @mohnstrudel в Heroku ветку нужно направить на новое приложение

**Comment by evgeny-matveev** [comment]
Запушил эту прямо в мейн, в следующих тасках буду делать в отдельных ветка и затем создавать пулрек

**Comment by evgeny-matveev** [comment]
⏰ 1 час

**Comment by mohnstrudel** [comment]
LGTM!
