### ISSUE TITLE
Remove supplier from product

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#10]
To-Do:

- нам поставщик не нужен в товаре, он нужен в закупке, так как один и тот же товар я могу покупать у разных поставщиков (проглядел при ревью)

**Comment by evgeny-matveev** [comment]
Мы добавили поставщиков в товар, чтобы видеть кто что может продать:
```ruby
product.suppliers # -> list all possible suppliers
supplier.products # -> possible products
```
Такой кейс полезен?

**Comment by mohnstrudel** [comment]
@evgeny-matveev К сожалению, нет) Эту информацию я чисто с сайтов у поставщиков беру.

Но таска сделана если я не ошибаюсь
