### ISSUE TITLE
Transfer products from our store to the store manager

### ISSUE THREAD

**Issue by evgeny-matveev** [mohnstrudel/store_manager_v2#15]
План:

- [x] Написать метод, который получает доступ к продуктам по апишке: авторизуется и получает продукты
- [x] Написать метод, который приводит полученные данные к нужному нам виду
- [x] Написать метод, который при помощи предыдущих методов переносит продукты к нам в базу данных
- [x] Запустить? Как мы его будет использовать?

**Comment by mohnstrudel** [comment]
Мне кажется нам этот метод понадобится только для первоначального заполнения базы, ведь все последующие товары мы будет создавать по вебхуку?

По поводу справочника - я думаю давай использовать только англ. названия:
- название цветов - black, blue, white, gold, red
- размеры (1:1, 1:2 и тд) - 1:1, 1:2, 1:3, 1:4, 1:6 самые основные
- формы (Bust, Statue) - больше нет)
- версии - exclusive, regular, deluxe, vip

**Comment by evgeny-matveev** [comment]
@mohnstrudel Да, этот метод для того, чтобы первично перенести товары в продакшн-базу админки. Затем будем получать новые по хуку.

Скорее всего перенос потребуется один раз. Однако пока админка еще не полно-функциональная, то есть шанс, что мы захотим дропнуть данные и пересоздать базу.

Я за использовать только английские названия. Есть сложность: как я перенесу существующие товары, если они сейчас на немецком? Мне нужен справочник, чтобы привести данные из одного вида в другой: из текущего немецкого в английский.

Словарь может пригодится и в хуках, если будет переходный этап, когда мы еще будем продолжать получать новые продукты на немецком.
