### ISSUE TITLE
BAR: Orders for a given product

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#17]
Идея:

- на странице товара видеть все заказы, сгруппированные по двум статусам к этому товару и общее кол-во заказов (цифру)
  - это кажется уже есть?
- статусы, по которым группируем - versendet (shipped или технически это наверное "closed" будет) и вторая группа - все остальные
  - вот этого, вроде, нет

**Comment by evgeny-matveev** [comment]
1. Заказы на странице отсортированы по дате: от самой свежей к самой старой. 
2. Число заказов я добавил.
3. Заказы отфильтрованы по статусу:

```ruby
active_statuses = [
   "partially-paid",
   "po_fully_paid",
   "pre-ordered",
   "processing",
   "ready-to-fullfill",
   "im-zulauf",
   "container-shipped"
]
```
4. Среди всех статусов нет versendet, shipped или closed. Есть completed, используем его или ты хочешь добавить новый статус в данные Ву и наши?

```ruby
all_statuses = [
   "cancelled",
   "completed",
   "container-shipped",
   "failed",
   "im-zulauf",
   "on-hold",
   "partial-shipped",
   "partially-paid",
   "po_fully_paid",
   "pre-ordered",
   "processing",
   "ready-to-fullfill",
   "refunded",
   "updated-tracking"
]
```

**Comment by evgeny-matveev** [comment]
В итоге можем сделать вот так:

![Image](https://github.com/mohnstrudel/store_manager_v2/assets/3902312/4f59f232-ccb7-4c47-b439-0f70fe4fae64)

Что думаешь? Какая информация о заказе или покупателе тебе важна в данном месте стор-мейта?
