### ISSUE TITLE
Move admin menu entries to a sub-level

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#24]
To-Do:

- сместить все пункты меню из `admin` неймспейса в отдельный пункт меню ("settings" или "admin"), где suppliers, brands, ... будут в выпадающем списке (т.е. сделать их на втором уровне вместо первого как сейчас)
- сейчас уже достаточно много пунктов, глаз разбегается немного 

![Image](https://github.com/mohnstrudel/store_manager_v2/assets/6050627/ec72035b-9ff5-4d51-8795-35fd0beb8bcd)

**Comment by evgeny-matveev** [comment]
Прятать пункты в меню усложняет UX. Вместо двух действий будет три: навести на меню, навести на пункт, кликнуть.

Меню сделать не сложно, но если проблема в том, что разбегаются глаза, то мы можем добавить пустоты — облегчить меню:
<img width="1512" alt="image" src="https://github.com/mohnstrudel/store_manager_v2/assets/3902312/04236f72-ef39-4093-a3df-5d5582dc7e12">

Прятать пункты в меню усложняет UX, но это разумный компромисс когда, например, мы скрываем разделы сайта, которые нужны малое количество раз в месяц.

Как думаешь, что будет тебе удобнее?

**Comment by mohnstrudel** [comment]
@evgeny-matveev Сорри, только сейчас увидел комментарий(

> Прятать пункты в меню усложняет UX, но это разумный компромисс когда, например, мы скрываем разделы сайта, которые нужны малое количество раз в месяц.

С теми пунктами именно так и есть) Но ты это и так уже сделал, я закрываю таску.
