### ISSUE TITLE
Create model "purchases" + views

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#4]
В тикете #3 мы создали модель "payments".

To-Do:

- создать модель "оплата" (payment) - один атрибут, value: float
- создать модель "purchase" (это наша закупка у поставщика)
- следующие атрибуты:
  - supplier: belongs_to
  - product: has_one/belongs_to
  - payment: has_many
  - order_number: string
  - paid: float
  - price: float
  - amount: integer
- создать вьюхи для purchase (у payment нет отдельных вьюх)

Описание вьюх:

Я хочу иметь возможность просматривать список закупок, отдельную закупку, удалять/редактировать закупку. На странице закупки у меня должна быть возможность просматривать значения закупки (каждого отдельного поля), т.е. 
Поставщик: Такой-то
Мой номер заказа у поставщика: такой-то

и иметь возможность вносить N-ое кол-во оплат (payments) для этого товара. При нажатии на "добавить оплату" желательно обновлять только область со списком оплат и не перезагружать всю страницу.

Далее я хочу видеть задолженность мою перед поставщиком за данный товар в общем (т.е. за всё кол-во, если я купил, например, 10 фигурок) и задолженность за одну штуку.

Приложил скрин из прототипа - https://excalidraw.com/#room=25d479070c6a37f9c658,aKO1uecured02tje0WXPYQ

**Comment by evgeny-matveev** [comment]
Вкратце о чем договорились в телеграме:
- `paid: float` не делаем, ведем учет платежи через `Payment`
- `order_number` → `order_reference`
- показать прогресс оплаты, чтобы визуально считывать сколько уже оплачено, например, через прогресс-бар
- показать величину остатка задолженности, чтобы не считать самому
- показать общую стоимость закупки
- добавить дату фактической оплаты, но по умолчанию приравнять к дню создания платежа
