### ISSUE TITLE
Decide how to use API with Wordpress (WooCommerce)

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#6]
To-Do:

- пошерстить интернет - как лучше взаимодействовать с WooCommerce. Думаю основные две опции:
  - после заказа или изменения статуса заказа нам WooCommerce шлет get/post 
  - мы периодически отправляем на сайт get реквесты

**Comment by evgeny-matveev** [comment]
Мы можем создать вебхук, который будет отправлять информацию о заказе на наш сервер, В WooCommerce есть хуки — как в рельсах или реакте — вызовы функций на определенных этапах цикла программы. На этой странице ты сможешь добавить хук order_created: https://woocommerce.com/document/webhooks/

---
Еще вариант. В WC можно добавлять свой собственный код почти на любом шаге. Например, когда покупатель оформил заказ, магазин показывает последним шагом страницу "спасибо": https://woocommerce.github.io/code-reference/files/woocommerce-templates-checkout-thankyou.html

А вот место в документации, где написано, как встроить в "спасибо" произвольный код: https://woocommerce.com/document/custom-tracking-code-for-the-thanks-page/

Эту же технику можно применить для добавления кастомных хуков.

---
Прочие ресурсы:
Инструкция по включению апишки: https://woocommerce.com/document/woocommerce-rest-api/
Описание апишки заказов: https://woocommerce.github.io/woocommerce-rest-api-docs/#orders
Гем для работы с апишкой: https://rubygems.org/gems/woocommerce_api

**Comment by evgeny-matveev** [comment]
В итоге:
1. Создаем эндпоинт в админке, который будет ожидает пост-запрос с данными о заказе.
2. Создаем вебхук в админке магазина, который будет присылать данные о заказе на эндпоинт из первого пункта.

В эндпоинт нужно будет встроить верификацию хука по секретному ключу, чтобы злоумышленники не могли нам присылать фейковые данные.

**Comment by evgeny-matveev** [comment]
Вебхук решит вопрос наполнения админки новыми заказами. Если нам нужно получить данные предыдущих заказов, то это другая история. Для нее мы должно выбрать: хотим ли мы разово выгрузить данные или автоматизировать.

Если разово, то я представляю себе процесс так:
- например, делаем запросом к апишке (через любую программу)
- сохраняем джейсон в файл
- парсим файл из рельс

По идее из разового решения родится задел на автоматизацию — парсинг файла все равно нужно писать. Возможно, что так и стоит сделать, а если задача повториться, то доделать в полноценный интерфейс.

**Comment by mohnstrudel** [comment]
Пока накидаю свои мысли, позже думаю надо будет созвониться и структурировать твои и мои.

> Например, когда покупатель оформил заказ, магазин показывает последним шагом страницу "спасибо"
У меня стоит плагин автоматизации и как показывает практика, к сожалению, это вообще не всегда так. Разные роли (гость/зареганный пользователь) получают разные страницы. Если ты платишь через third-party (например сервис оплаты в кредит от EasyCredit), то страница тоже другая. Итого там какой-то ворох разных страниц.

Лучше использовать "классический" триггер - именно создание сущности "заказ" на уровне базы данных.

> Если нам нужно получить данные предыдущих заказов, то это другая история. 
Данные обязательно надо будет получить, хоть и может быть одноразово, так как сейчас проблема острая и я бы хотел её решить и для заказов, которые уже пришли к нам до появления Store Manager.

Я сейчас скорее за вебхук, только надо будет ещё проверить, работает ли он при смене статуса заказа. Так как если я отправляю заказ, то это его финальная стадия и его жизненный цикл закончился. В SM надо будет перестать учитывать этот заказ для всех возможных расчетов.

**Comment by evgeny-matveev** [comment]
Пишут, что хук можно сделать на смену статуса заказа:

> On webhook settings you just need to pick `Action`, and then use `woocommerce_order_status_completed` or any other action to when the order is complete.

Взял [из обсуждения](https://github.com/woocommerce/woocommerce/issues/20336) на Гитхабе. Сложность подхода с кастомным ивентом в том, что нужно самим написать функцию, которая шлет информацию о заказе.

Я бы сначала проверил, как работают встроенные хуки — может там есть хук, который реагирует на любую смену статуса заказа. Нам такой подошел бы, мы со стороны бекенда можем отфильтровать ненужные события.

**Comment by mohnstrudel** [comment]
> Я бы сначала проверил, как работают встроенные хуки — может там есть хук, который реагирует на любую смену статуса заказа. Нам такой подошел бы, мы со стороны бекенда можем отфильтровать ненужные события.

Я думаю вот это будет вообще идеально.

**Comment by evgeny-matveev** [comment]
Я посмотрел встроенный хук `Order updated`, он срабатывает на любое изменение статуса заказа и присылает полную информацию по нему пост-запросом.

![Image](https://github.com/mohnstrudel/store_manager_v2/assets/3902312/f93c07a4-b4ee-4f34-9630-d6296f00b646)

На скриншоте видны все статусы, на которых срабатывает вебхук. Вот тело запроса:
```json
{
    "id": 64,
    "parent_id": 0,
    "status": "completed",
    "currency": "USD",
    "version": "8.0.1",
    "prices_include_tax": false,
    "date_created": "2023-08-13T16:40:58",
    "date_modified": "2023-08-13T16:55:45",
    "discount_total": "0.00",
    "discount_tax": "0.00",
    "shipping_total": "0.00",
    "shipping_tax": "0.00",
    "cart_tax": "0.00",
    "total": "0.00",
    "total_tax": "0.00",
    "customer_id": 0,
    "order_key": "wc_order_WcK7daQRdWPiV",
    "billing": {
        "first_name": "",
        "last_name": "",
        "company": "",
        "address_1": "",
        "address_2": "",
        "city": "",
        "state": "",
        "postcode": "",
        "country": "",
        "email": "",
        "phone": ""
    },
    "shipping": {
        "first_name": "",
        "last_name": "",
        "company": "",
        "address_1": "",
        "address_2": "",
        "city": "",
        "state": "",
        "postcode": "",
        "country": "",
        "phone": ""
    },
    "payment_method": "",
    "payment_method_title": "",
    "transaction_id": "",
    "customer_ip_address": "",
    "customer_user_agent": "",
    "created_via": "admin",
    "customer_note": "",
    "date_completed": "2023-08-13T16:53:44",
    "date_paid": "2023-08-13T16:42:19",
    "cart_hash": "",
    "number": "64",
    "meta_data": [
        {
            "id": 410,
            "key": "_automatewoo_order_created",
            "value": "1"
        },
        {
            "id": 415,
            "key": "minmax_do_not_count",
            "value": ""
        }
    ],
    "line_items": [],
    "tax_lines": [],
    "shipping_lines": [],
    "fee_lines": [],
    "coupon_lines": [],
    "refunds": [],
    "payment_url": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/checkout/order-pay/64/?pay_for_order=true&key=wc_order_WcK7daQRdWPiV",
    "is_editable": false,
    "needs_payment": false,
    "needs_processing": false,
    "date_created_gmt": "2023-08-13T08:40:58",
    "date_modified_gmt": "2023-08-13T08:55:45",
    "date_completed_gmt": "2023-08-13T08:53:44",
    "date_paid_gmt": "2023-08-13T08:42:19",
    "gift_cards": [],
    "currency_symbol": "$",
    "_links": {
        "self": [
            {
                "href": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/wp-json/wc/v3/orders/64"
            }
        ],
        "collection": [
            {
                "href": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/wp-json/wc/v3/orders"
            }
        ]
    },
    "controller": "webhook",
    "action": "order",
    "webhook": {
        "id": 64,
        "parent_id": 0,
        "status": "completed",
        "currency": "USD",
        "version": "8.0.1",
        "prices_include_tax": false,
        "date_created": "2023-08-13T16:40:58",
        "date_modified": "2023-08-13T16:55:45",
        "discount_total": "0.00",
        "discount_tax": "0.00",
        "shipping_total": "0.00",
        "shipping_tax": "0.00",
        "cart_tax": "0.00",
        "total": "0.00",
        "total_tax": "0.00",
        "customer_id": 0,
        "order_key": "wc_order_WcK7daQRdWPiV",
        "billing": {
            "first_name": "",
            "last_name": "",
            "company": "",
            "address_1": "",
            "address_2": "",
            "city": "",
            "state": "",
            "postcode": "",
            "country": "",
            "email": "",
            "phone": ""
        },
        "shipping": {
            "first_name": "",
            "last_name": "",
            "company": "",
            "address_1": "",
            "address_2": "",
            "city": "",
            "state": "",
            "postcode": "",
            "country": "",
            "phone": ""
        },
        "payment_method": "",
        "payment_method_title": "",
        "transaction_id": "",
        "customer_ip_address": "",
        "customer_user_agent": "",
        "created_via": "admin",
        "customer_note": "",
        "date_completed": "2023-08-13T16:53:44",
        "date_paid": "2023-08-13T16:42:19",
        "cart_hash": "",
        "number": "64",
        "meta_data": [
            {
                "id": 410,
                "key": "_automatewoo_order_created",
                "value": "1"
            },
            {
                "id": 415,
                "key": "minmax_do_not_count",
                "value": ""
            }
        ],
        "line_items": [],
        "tax_lines": [],
        "shipping_lines": [],
        "fee_lines": [],
        "coupon_lines": [],
        "refunds": [],
        "payment_url": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/checkout/order-pay/64/?pay_for_order=true&key=wc_order_WcK7daQRdWPiV",
        "is_editable": false,
        "needs_payment": false,
        "needs_processing": false,
        "date_created_gmt": "2023-08-13T08:40:58",
        "date_modified_gmt": "2023-08-13T08:55:45",
        "date_completed_gmt": "2023-08-13T08:53:44",
        "date_paid_gmt": "2023-08-13T08:42:19",
        "gift_cards": [],
        "currency_symbol": "$",
        "_links": {
            "self": [
                {
                    "href": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/wp-json/wc/v3/orders/64"
                }
            ],
            "collection": [
                {
                    "href": "https://woo-unabashedly-legendary-ruins.wpcomstaging.com/wp-json/wc/v3/orders"
                }
            ]
        }
    }
}/
```

**Comment by evgeny-matveev** [comment]
@mohnstrudel Мне нужны примеры реальных данных из магазина, чтобы я смог понять, как сделать продажи и клиентов. Магазин будет присылать нам данных с избытком, что из них нам нужно дублировать у себя в базе данных?

**Comment by mohnstrudel** [comment]
Итак, самое важное от заказа:
- Дата создания
- Статус заказа
- Адрес для отправки счета
- Адрес для доставки товара (в 80% случаев они одинаковые, но есть 20%, когда они различаются и это важно)
- Мейл & телефон
- список товаров
- стоимость доставки

<img width="1231" alt="Monosnap Bestellung bearbeiten „Order – August 8, 2023 @ 10:01 AM“ ‹ HandsomeCake Goodies — WordPress 2023-08-14 10-28-50" src="https://github.com/mohnstrudel/store_manager_v2/assets/6050627/ef001110-c89e-4bf8-a28e-4cd470fe765d">
