### ISSUE TITLE
Create purchase "debt" overview

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#9]
To-Do:

- необходим список товаров, которые у меня купили клиенты, но я не закупил у поставщиков
- можно в принципе попробовать реализовать на уже существующий странице товаров, но конечно хотелось бы видеть отдельным списком
- список можно сортировать по кол-ву "задолженности", т.е. я хочу иметь возможность увидеть тот товар сверху, самое большое кол-во которого я ещё должен купить
- show view не нужно
- удалять/редактировать список нельзя
- товары должны сами пропадать из этого списка, как только я совершаю заказ у поставщика на этот товар (закупку) либо кол-во задолженности уменьшается

**Comment by evgeny-matveev** [comment]
Anton:

> Я вижу так - при закупке товара (т.е. я закупаю у поставщика) я ручками заношу данные о закупке. Т.е. я выбираю товар из базы (либо создаю новый) и создаю сущность "закупка". В идеале у меня всегда должно быть как на весах, ровно в закупках и в продажах. И задолженность - это по факту показатель, куда перевес в этих весах.
> 
> Т.е. вот есть продажи на фигурку ABC -> 3 x ABC и есть две закупки на эту же фигурку -> 2 x ABC:
> 3 x ABC  <==> 2 x ABC ага, мне тут должно в этом списке показать ABC и что я должен купить ещё одну
> Ну а на дашборде мы просто аккумулируем эту информацию

**Comment by evgeny-matveev** [comment]
No payments в закупке — это редкий случай, но важный:

> Бывает такое - я создаю заказ, но оплатить, например сразу Пейпалом я не могу. И прошу китайца выставить мне счет через одну систему. Потом как обычно - день-другой, дети, жена, я забыл, китаец забыл, мой заказ у него как неоплачен и я фигурки просвестел


В большинстве случаев мы не увидим эту таблицу — вместо нее будем растягивать соседнюю таблицу Payment is due

No purchases будет снизу на весь экран
