### ISSUE TITLE
A: Add purchase check for sales

### ISSUE THREAD

**Issue by mohnstrudel** [mohnstrudel/store_manager_v2#92]
Зачем:

- когда я просматриваю продажу, мне сейчас нужно совершить сразу несколько действий, чтобы понять - нужно ли мне действовать в плане закупок. Т.е. я захожу в продажу и потом в /debts и ищу уже этот товар, либо на страницу товара и смотрю, сколько есть закупок и сколько продаж

To-Do:
- по методу first in, first out посчитывать для каждой продажи, есть ли для нее закупка, т.е. "покрыта" ли эта продажа закупкой
- создать связь "sale_purchase", где к конкретной продаже мы будем прикреплять конкретную закупку
- думаю лучше пересчитывать каждый раз, когда приходит новая продажа и новая закупка

Пример:
- есть 10 закупок Batman и 8 продаж
- приходит 9-ая продажа. Мы ставим проставляем ей айди закупки под номером 9 (просто девятой по счету)
- приходит 10-ая продажа. Мы также ставим ей айди закупки под номером 10
- приходит 11-ая продажа. Мы ставим ей, например флажок "не покрыта закупкой", ну или просто поле будет `nil`
- на странице /sales покрытые как-то отмечаем зеленым (можно новую колонку и использовать элементы-тэги), а непокрытые - красным
- соответственно функционал {debt} можно переписать под эти флажки/под это поле, будет, наверное, проще

**Comment by evgeny-matveev** [comment]
@mohnstrudel Я частично сделал эту задачу в рамках задачи по складам. Поэтому давай доделаем ее перед #102.

Сначала предлагаю убедиться, что мы правильно друг друга понимаем.

**В чем задача.** Нужна возможность связывать продажи и закупки.

Примеры:
- Клиент купил товар.
- В админке появилась новая продажа.
- Мы перешли на список продаж:
	- Как понять, какие продажи связаны с закупками, а какие — нет?
- Мы перешли на страницу продажи:
	- Как нам понять, связана ли продажа с закупками?
	- Как ее связать с закупками?
	- Как изменить ее связь?
- Мы перешли на страницу закупки:
	- Как понять, что к закупке привязаны продажи?
	- Как привязать или отвязать?
	- Как понять, есть ли еще свободные, не привязанные продажи?

**Подзадача.** Сделать так, чтобы закупки привязывались к продажам сразу после создания закупки. Например, мы создали закупку. Затем наша система ищет самую старую продажу и связывает её с закупкой.

**Comment by mohnstrudel** [comment]
Отвечаю на вопросы с точки зрения бизнес-логики:

1. Как понять, какие продажи связаны с закупками, а какие — нет?
  1. Это должно работать по принципу FiFo - first in, first out. Т.е. пример:
  2. Вася купил товар А в январе 2022 года
  3. Петя купил товар А в феврале 2022 года
  4. Маша купила также товар А в декабре 2022 года
  5. Я делаю закупку на 2 товара А (т.е. один из клиентов уходит с ничем). Получается так как Вася и Петя купили товар раньше Маши, мы им "прикрепляем" закупки, а у Маши ничего нет.
2. Мы перешли на страницу продажи - Как нам понять, связана ли продажа с закупками?
  1. В идеале как-то так:
  2. ![Image](https://github.com/user-attachments/assets/45ab039e-3b6e-4ef5-9b44-d5d571ed01e6)

3. Как ее связать с закупками? - см. принцип выше. Если в ручном режиме, то на странице редактирования должна быть возможность выбрать закупку, либо открепить уже существующую
4. Мы перешли на страницу закупки - Как понять, что к закупке привязаны продажи?
  1. Логика обработки такая же (см. выше)
  2. Визуально в идеале вот тут выводить информацию: 
  3. ![Image](https://github.com/user-attachments/assets/d505658d-198f-4247-b308-b80d5fc84289)
5. Как привязать или отвязать? - думаю также, на странице редактирования удаляем связь либо добавляем вручную
6. Как понять, есть ли еще свободные, не привязанные продажи? - именно на странице закупки в этой информации, кажется, смысла нет. Ведь если скрипт/метод работает, то там либо точно будут продажи, либо, если этой информации там не будет, значит на эту закупку ещё нет продажи. Я иногда бывает покупаю "впрок".

**Comment by evgeny-matveev** [comment]
@mohnstrudel У меня появился вопрос по закупкам, который можно решать в отдельной задаче.

Мы изменили amount (число закупленных товаров) в закупке (purchase) — что делать:
- Создавать новый purchased product и добавить на склад по умолчанию?
- Какой purchased product удалить, а какой оставить, если мы убавили amount?
- А если purchased product связан с product sale, то что делаем?
- Что говорим клиентам? Им же пришло оповещение, что товар на таком-то складе.
